### ISSUE TITLE
Compiled SCSS does not update on production if no changes to the base file.

### ISSUE THREAD

**Issue by rblackman** [ligershark/WebOptimizer.Sass#24]
If you publish a SCSS file to a server (I have tried on IIS 10, not sure about others) and it imports another SCSS file, the CSS correctly initially. However, if you update the imported file without making any changes to the parent file, it will not detect these changes upon republish. Once you make a change to the parent file, it will pick up changes in both files.

#### Directory Structure
```
| startup.cs
| wwwroot\scss\
    | sub-file.scss
    | styles.scss
```

#### sub-file.scss

```scss
body {
  color: red;
}
```

#### styles.scss

```scss
@import './sub-file.scss';
```

#### startup.cs

```cs
...

var isProduction = _environment.IsProduction();
services.AddWebOptimizer(
        _environment,
        new CssBundlingSettings { Minify = isProduction }, new CodeBundlingSettings { Minify = isProduction },
        pipeline =>
        {
            _ = pipeline.AddScssBundle("/css/styles.css", "scss/styles.scss");
        }
);
...
```

#### sub-file.scss

```scss
body {
  color: blue;
}
```

This change will not be reflected on the server. However, as soon as you make this change, it will pick up the changes in the referenced file.

#### styles.scss

```scss
@import './sub-file.scss';
// foo
```

**Comment by frederikstonge** [comment]
Fixed in #25

**Comment by westbrma** [comment]
> Fixed in #25

I just updated to the latest version `3.0.58-beta` (published same day as the fix merge) I still have the issue after changing an imported scss file, the bundle is not updated

**Comment by frederikstonge** [comment]
Do you still have a css file in wwwroot/css called styles.css?

**Comment by westbrma** [comment]
nope (this is another person btw) i have a `site.scss` which imports `_layout.scss` both located in `wwwroote/css`

**Comment by westbrma** [comment]
I have the problem, i had to change this `pipeline.AddScssBundle("/css/site.css", "/css/site.scss").UseFileProvider(provider);`
to this `pipeline.AddScssBundle("/css/site.css", "css/site.scss").UseFileProvider(provider);`

**Comment by frederikstonge** [comment]
I think that will fix the foward slash problem #28

**Comment by westbrma** [comment]
still not working, I created a test project against your branch, `Compiler.ExecuteAsync` only gets invoked when there is a change the the parent scss file

**Comment by frederikstonge** [comment]
Damn, FileVersionProvider doesn't use the GenerateCacheKey method from IAsset but does a hash of the content of the file... I will have to go back to the drawing board.

**Comment by westbrma** [comment]
I believe this is the same issue reported here: [](https://github.com/ligershark/WebOptimizer.Sass/issues/3)

**Comment by westbrma** [comment]
this is a hack but seems to work, basically whenever a scss file is changed, we touch one of the source files in the asset. This could be made more robust by auto detecting the paths to watch. I'm really confused about the `CacheKey` method, I'm not sure why this is needed and why its being called 2x for every page refresh. Its also costly using the GenerateCacheKey. Seems the core could just compute a hash on the resulting files.

private System.IO.FileSystemWatcher mWatcher;
`private void CreateWatcher(IFileProvider fileProvider)
{
	mWatcher = new System.IO.FileSystemWatcher();
	var firstFile = _asset.SourceFiles.First();
	var file = fileProvider.GetFileInfo(firstFile);
	mWatcher.Path = Path.GetDirectoryName(file.PhysicalPath);
	mWatcher.Filter = "*.scss";
	mWatcher.NotifyFilter = NotifyFilters.LastWrite;
	mWatcher.Changed += (e, b) =>
	{
		if (b.FullPath == file.PhysicalPath) return;
		System.IO.File.SetLastWriteTimeUtc(file.PhysicalPath, DateTime.UtcNow);
	};
	mWatcher.EnableRaisingEvents = true;
}`

**Comment by frederikstonge** [comment]
Yeah, I don't get why we generate a cache key different from the path of the file itself. Technically, we don't want to cache multiple version of the same file. My guess would be that each request should strip the version of the file to generate the cacke hey (/css/styles.css), then compute hash on that result, and verify that the version matches, if not, regenerate a new one, place in cache and return this one.

**Comment by erdemgezer** [comment]
Hi, having the same issue :( any luck with fixing this?

**Comment by zaclic** [comment]
Same issue here as well. Will this be fixed?

**Comment by htodep** [comment]
Whats the status of this bug? Also having the same issues. The parameter on the CSS url is not updated when scss partials are changed.

**Comment by benjstern** [comment]
I've tested all versions from the **58beta** to **master** and it seems the bug is alive and well. 

From what I can tell it seems a little odder than I was expected because when having changed a partial and launching my web application with developer tool initiated and watching the network, the first time the file is requested I get a _unique id_ on subsequent requests of the page it seems to _revert to the id_ of just the main .scss file. _(This is an assumption based of multiple tests haven't yet stepped through the logic)_

This is highly irregular and seems like a pretty nasty bug somewhere in the logic the generation of the key breaks and bad.

Is this bug targeted for fix? Is the maintainer of this repository active or present?

**Comment by benjstern** [comment]
@htodep, @erdemgezer , @zaclic maybe you can test my pull request and confirm if this issue would be resolved, seems to work on my end.

**Comment by zaclic** [comment]
@benjamin-stern I tried version 3.0.82-beta (which I believe must have your change) and it worked. Thanks heaps! ❤️
